### ISSUE TITLE
Errors running with coverage[toml]

### ISSUE THREAD

**Issue by philgyford** [TheKevJames/coveralls-python#356]
I've had coverage and coveralls working fine in [a GitHub Action](https://github.com/philgyford/django-hines/blob/main/.github/workflows/main.yml). I recently changed where I keep coverage's config, from `setup.cfg` to `.pyproject.toml`, and installed `coverage[toml]`.

But now when coveralls runs I get the errors below. Is there a way for it to work with `coverage[toml]` instead of vanilla `coverage`?

```
Run coveralls debug --service=github
[2](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:2)
  coveralls debug --service=github
[3](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:3)
  shell: /usr/bin/bash -e {0}
[4](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:4)
  env:
[5](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:5)
    pythonLocation: /opt/hostedtoolcache/Python/3.10.5/x64
[6](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:6)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.5/x64/lib
[7](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:7)
    GITHUB_TOKEN: ***
[8](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:9)
Missing .coveralls.yml file. Using only env variables.
[9](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:10)
Testing coveralls-python...
[10](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:11)
Traceback (most recent call last):
[11](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:12)
  File "/opt/pipx_bin/coveralls", line 8, in <module>
[12](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:13)
    sys.exit(main())
[13](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:14)
  File "/opt/pipx/venvs/coveralls/lib/python3.8/site-packages/coveralls/cli.py", line 75, in main
[14](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:15)
    coverallz.wear(dry_run=True)
[15](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:16)
  File "/opt/pipx/venvs/coveralls/lib/python3.8/site-packages/coveralls/api.py", line 254, in wear
[16](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:17)
    json_string = self.create_report()
[17](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:18)
  File "/opt/pipx/venvs/coveralls/lib/python3.8/site-packages/coveralls/api.py", line 332, in create_report
[18](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:19)
    data = self.create_data()
[19](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:20)
  File "/opt/pipx/venvs/coveralls/lib/python3.8/site-packages/coveralls/api.py", line 386, in create_data
[20](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:21)
    self._data = {'source_files': self.get_coverage()}
[21](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:22)
  File "/opt/pipx/venvs/coveralls/lib/python3.8/site-packages/coveralls/api.py", line 400, in get_coverage
[22](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:23)
    workman = coverage.coverage(config_file=config_file)
[23](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:24)
  File "/opt/pipx/venvs/coveralls/lib/python3.8/site-packages/coverage/control.py", line 246, in __init__
[24](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:25)
    self.config = read_coverage_config(
[25](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:26)
  File "/opt/pipx/venvs/coveralls/lib/python3.8/site-packages/coverage/config.py", line 561, in read_coverage_config
[26](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:27)
    config_read = config.from_file(fname, warn, our_file=our_file)
[27](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:28)
  File "/opt/pipx/venvs/coveralls/lib/python3.8/site-packages/coverage/config.py", line 277, in from_file
[28](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:29)
    files_read = cp.read(filename)
[29](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:30)
  File "/opt/pipx/venvs/coveralls/lib/python3.8/site-packages/coverage/tomlconfig.py", line 66, in read
[30](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:31)
    raise ConfigError(msg.format(filename))
[31](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:32)
coverage.exceptions.ConfigError: Can't read 'pyproject.toml' without TOML support. Install with [toml] extra
[32](https://github.com/philgyford/django-hines/runs/7433522069?check_suite_focus=true#step:8:33)
Error: Process completed with exit code 1.
```

**Comment by TheKevJames** [comment]
Can't seem to reproduce this, using dependencies `coverage[toml]` and `coveralls`. I'm just about to release a new `coveralls` version which has a bunch of cleanups; please try it out, and if you still see this issue go ahead and re-open the ticket. Please be sure to include all the relevant versions when you do so!
