### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by LostInDarkMath** [TheKevJames/coveralls-python#387]
I have a pipeline with coveralls that always works ha. Now it works only partially. I use Travic CI and test against several Python versions in parallel. With one version the coverage is transmitted correctly, with the others not. I find this very strange. Do you have any idea what could be the reason for this?

Link; https://github.com/LostInDarkMath/pedantic-python-decorators/pull/85/checks?check_run_id=14880937102

```
$ coveralls

Submitting coverage to coveralls.io...

Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/coveralls/api.py", line 290, in submit_report

    response.raise_for_status()

  File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/coveralls/cli.py", line 95, in main

    result = coverallz.wear()

             ^^^^^^^^^^^^^^^^

  File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/coveralls/api.py", line 257, in wear

    return self.submit_report(json_string)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/coveralls/api.py", line 293, in submit_report

    raise CoverallsException(

coveralls.exception.CoverallsException: Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
```

**Comment by afinetooth** [comment]
@LostInDarkMath (Cc: @TheKevJames) we had another user of coveralls-python report a similar `500` error yesterday. We're not sure what it is---we're not experiencing a general incident---but I have added this issue to our internal card and will update you here so we can hopefully get you and others a solution asap.

**Comment by LostInDarkMath** [comment]
Any news on this?

**Comment by TheKevJames** [comment]
Closing this one for now as stale -- if it happens again, and doesn't relate to a coveralls outage, we can dive into it then!
